"""Extract Sunshine's timer artwork/layout from an owned US ISO (no game code).

Generated textures retain the retail pixels and J2D pane transforms. Nothing
reads the ISO at runtime. The build consumes only the bounded generated header.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import struct
from pathlib import Path

from inspect_rarc_asset import decode_yaz0, rarc_files


def u16(b, p): return struct.unpack_from(">H", b, p)[0]
def u32(b, p): return struct.unpack_from(">I", b, p)[0]


def read_archive(path):
    with path.open("rb") as f:
        header = f.read(0x440)
        if header[:6] != b"GMSE01":
            raise ValueError("expected an owned GMSE01 Sunshine ISO")
        offset, size = struct.unpack_from(">II", header, 0x424)
        if size > 16 * 1024 * 1024: raise ValueError("oversize FST")
        f.seek(offset)
        fst = f.read(size)
        count = u32(fst, 8)
        strings = fst[count * 12:]
        for i in range(1, count):
            flags, offset, size = struct.unpack_from(">III", fst, i * 12)
            if flags >> 24: continue
            name_at = flags & 0xffffff
            name = strings[name_at:strings.index(0, name_at)]
            if name == b"game_6.szs":
                if size > 32 * 1024 * 1024: raise ValueError("oversize archive")
                f.seek(offset)
                data = f.read(size)
                return rarc_files(decode_yaz0(data))
    raise ValueError("game_6.szs missing")


def only(files, name):
    choices = [b for p, b in files.items() if p.rsplit("/", 1)[-1] == name]
    if len(choices) != 1: raise ValueError(f"ambiguous/missing {name}")
    return choices[0]


def panes(data):
    if data[:8] != b"SCRNblo1": raise ValueError("expected BLO1")
    result, parents, last, o = {}, [], None, 32
    while o + 8 <= len(data):
        kind, size = data[o:o+4], u32(data, o+4)
        if size < 8 or o + size > len(data): raise ValueError("invalid BLO chunk")
        if kind in (b"PAN1", b"PIC1", b"TBX1", b"WIN1"):
            p = o + 8
            count = data[p]
            tag = data[p+4:p+8].decode("ascii")
            x, y, w, h = struct.unpack_from(">hhhh", data, p+8)
            angle = u16(data, p+16) if count >= 7 else 0
            anchor = data[p+18] if count >= 8 else 0
            alpha = data[p+19] if count >= 9 else 255
            pane = dict(tag=tag, parent=parents[-1] if parents else None,
                        rect=[x,y,w,h], angle=angle, anchor=anchor, alpha=alpha)
            if kind == b"PIC1":
                pos = (p + 16 + (2 if count >= 7 else 0) +
                       (1 if count >= 8 else 0) + (1 if count >= 9 else 0) +
                       (1 if count >= 10 else 0) + 3) & ~3
                n = data[pos]
                pos += 1
                refs = []
                for _ in range(2):
                    length = data[pos+1]
                    refs.append(data[pos+2:pos+2+length].decode("ascii"))
                    pos += 2 + length
                pane.update(texture=refs[0], palette=refs[1], binding=data[pos],
                            mirror=data[pos+1] if n >= 4 else 0,
                            wrap=data[pos+2] if n >= 5 else 0,
                            black=u32(data,pos+3) if n >= 6 else 0,
                            white=u32(data,pos+7) if n >= 7 else 0xffffffff,
                            colours=[u32(data,pos+11+i*4) if n >= 8+i else 0xffffffff for i in range(4)])
            result[tag] = pane
            last = tag
        elif kind == b"BGN1": parents.append(last)
        elif kind == b"END1": parents.pop()
        elif kind == b"EXT1": break
        o += size
    return result


def emit_header(files, tree, output):
    names = [f"coin_number_{n}.bti" for n in range(10)] + [
        "coin_number_colon.bti", "time_text.bti", "coin_back.bti"]
    lines = ["// Generated by extract_lm_timer_assets.py from an owned GMSE01 ISO.",
             "#ifndef LM_TIMER_ASSETS_HXX", "#define LM_TIMER_ASSETS_HXX",
             "struct LmTimerTexture { unsigned short width, height; unsigned char format; const unsigned char *data; };",
             "struct LmTimerPane { short x, y, width, height, cosine, sine; unsigned char texture, alpha; };"]
    records = []
    for index, name in enumerate(names):
        b = only(files, name)
        fmt, w, h, at = b[0], u16(b, 2), u16(b, 4), u32(b, 28)
        if fmt not in (0, 5) or w > 256 or h > 256:
            raise ValueError(f"unexpected texture format or extent: {name}")
        length = ((w+7)//8)*((h+7)//8)*32 if fmt == 0 else ((w+3)//4)*((h+3)//4)*32
        raw = b[at:at+length]
        if len(raw) != length: raise ValueError("short texture")
        lines.append(f"// {name}; original BTI SHA256 {hashlib.sha256(b).hexdigest()}")
        lines.append(f"static const unsigned char kLmTimerTexture{index}[] = {{")
        lines += ["    " + ",".join(f"0x{v:02x}" for v in raw[p:p+24]) + "," for p in range(0,len(raw),24)]
        lines.append("};")
        records.append(f"    {{{w},{h},{fmt},kLmTimerTexture{index}}},")
    lines += ["static const LmTimerTexture kLmTimerTextures[] = {"] + records + ["};"]
    tags = ["t_n1", "t_n2", "t_c1", "t_n3", "t_n4", "t_c2", "t_n5", "t_n6", "t_tx", "t_ba"]
    lines.append("static const LmTimerPane kLmTimerPanes[10] = {")
    for tag in tags:
        p = tree[tag]
        x, y, w, h = p["rect"]
        parent = p["parent"]
        while parent != "\0t_0":
            q = tree[parent]
            if q["angle"] or q["alpha"] != 255: raise ValueError("unexpected parent transform")
            x += q["rect"][0]
            y += q["rect"][1]
            parent = q["parent"]
        if p["anchor"] or p["mirror"] or p["binding"] != 15 or p["colours"] != [0xffffffff]*4:
            raise ValueError("unexpected picture transform/colour")
        angle = math.radians(-p["angle"])
        c, s = round(math.cos(angle)*16384), round(math.sin(angle)*16384)
        lines.append(f"    {{{x},{y},{w},{h},{c},{s},{names.index(p['texture'])},{p['alpha']}}}, // {tag}: -{p['angle']} degrees")
    lines += ["};", "#endif", ""]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))
    return sum(len(only(files,n))-32 for n in names)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("iso", type=Path)
    ap.add_argument("--header", type=Path)
    ap.add_argument("--report", type=Path)
    args = ap.parse_args()
    files = read_archive(args.iso)
    blo = only(files, "standard_1.blo")
    tree = panes(blo)
    selected = {k:v for k,v in tree.items() if k.startswith(("t_", "\0t_"))}
    textures = {p["texture"] for p in selected.values() if "texture" in p}
    report = dict(layout_sha256=hashlib.sha256(blo).hexdigest(), panes=selected,
                  textures={n:dict(header=only(files,n)[:32].hex(), bytes=len(only(files,n))) for n in sorted(textures)})
    if args.header:
        count = emit_header(files, tree, args.header)
        print(f"Generated {args.header}: {count} texture bytes, 10 retail panes")
    else:
        print(json.dumps(report, indent=2))
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, indent=2)+"\n")


if __name__ == "__main__": main()
