"""Regenerate the recovered GaddWarp placement constants, without retail assets."""

from __future__ import annotations

import argparse
import csv
import io
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def points() -> list[dict[str, str]]:
    text = (ROOT / "doc/gaddwarp-jp2.2-feature-port.md").read_text(encoding="utf-8")
    data = text.split("~~~csv\n", 1)[1].split("~~~", 1)[0]
    return list(csv.DictReader(io.StringIO(data)))


def render() -> str:
    lines = ["// Generated by scripts/gen_lm_warp_points.py from the recovered placement CSV."]
    for row in points():
        floats = [str(float(row[key])) + "f" for key in ("x", "y", "z", "yaw")]
        lines.append("    {%su, %su, %s}," % (row["id"], row["room_no"], ", ".join(floats)))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = ROOT / "lm_diag/src/lm_warp_points.inc"
    expected = render()
    if args.check:
        if output.read_text(encoding="utf-8") != expected:
            raise SystemExit("warp placement constants need regeneration")
    else:
        output.write_text(expected, encoding="utf-8", newline="\n")
